development:
    adapter: mysql
    database: test
    username: test
    password: test
    pool: 5
    timeout: 5000

test:
    adapter: mysql
    database: test
    username: test
    password: test
    pool: 5
    timeout: 5000


production:
    adapter: mysql
    database: test
    username: test
    password: test
    pool: 5
    timeout: 5000
